language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

before_script:
    - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source install

script: vendor/phpunit/phpunit/phpunit --configuration phpunit.xml-dist